version: '3'
services:
  publisher1:
    build:
      context: .
      dockerfile: publisher.Dockerfile
    networks:
      - kafka-net

  publisher2:
    build:
      context: .
      dockerfile: publisher.Dockerfile
    networks:
      - kafka-net

  subscriber1:
    build:
      context: .
      dockerfile: subscriber.Dockerfile
    networks:
      - kafka-net

  subscriber2:
    build:
      context: .
      dockerfile: subscriber.Dockerfile
    networks:
      - kafka-net

networks:
  kafka-net:
